### ISSUE TITLE
Not working bro 

### ISSUE THREAD

**Issue by Ashwani10101** [Marplex/CloudflareBypass#1]
I included provided Dependences and build.gradle seem normal but i cant find CloudflareHTTPClient() and can't create any object from it. Please help !!
![screenshot](https://user-images.githubusercontent.com/54770264/85283214-98d8b380-b4aa-11ea-8ab1-fde02a1e1c2c.png)

**Comment by Marplex** [comment]
I had some issues publishing the library, that's why you didn't find any class.
By the way the library is now broken because recently Cloudflare changed the IUAM page with more difficult challenges.
I'll try to understand them and find a solution. The new challenge seems pretty hard to solve/reverse engineer so I might give up and deprecate this project.

**Comment by Ashwani10101** [comment]
Best of luck bro, Only pro's like you can do this, It's hard to believe community could not figured it out, This library is closest thing we have, If they can change IUAM once they can do it again so don't sweat it out

**Comment by smallshen** [comment]
The issue was the name of  the package, the package start is "it" which is a keyword in kotlin
