### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by andress134** [Marplex/CloudflareBypass#3]
hello sir @Marplex can u offer support for nodejs or golang?

**Comment by Marplex** [comment]
Hi, cloudflare changed the challenges of the iuam page and, for now, the library is not working.
I'm trying to reverse engineer it and hopefully fix the lib.
My goal now is to bypass cloudflare without using an headless browser. The problem is that the new challenge uses DOM, Ajax and other "browser related" components. I will have to implement those on Mozilla Rhino.
